# Site settings
title: personal
email: 1007530194@qq.com
description: "nothing"
baseurl: ""
url: "https://1007530194.github.io/Diary/"
twitter_username: 1007530194
github_username:  1007530194

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

