copyright: Copyright &copy; 2016 - 2018 Martin Donath
edit_uri: ''
extra:
  social:
  - link: http://struct.cc
    type: globe
  - link: https://github.com/1007530194
    type: github-alt
  - link: https://twitter.com/1007530194
    type: twitter
  - link: https://linkedin.com/in/1007530194
    type: linkedin
extra_javascript:
- https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
markdown_extensions:
- markdown.extensions.admonition
- markdown.extensions.codehilite:
    guess_lang: false
    linenums: true
- markdown.extensions.def_list
- markdown.extensions.footnotes
- markdown.extensions.meta
- markdown.extensions.toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
pages:
- Home: ToDo.md
- Home:
  - AboutMe.md
  - index.md
  - Nothing.md
  - ToDo.md
- 书籍:
  - 书籍/index.md
  - 机器学习实战:
    - 书籍/机器学习实战/00naive-bayes-discuss.md
    - 书籍/机器学习实战/01.机器学习基础.md
    - 书籍/机器学习实战/02.k-近邻算法.md
    - 书籍/机器学习实战/03.决策树.md
    - 书籍/机器学习实战/04.朴素贝叶斯.md
    - 书籍/机器学习实战/05.Logistic回归.md
    - 书籍/机器学习实战/06.0.支持向量机.md
    - 书籍/机器学习实战/06.1.支持向量机的几个通俗理解.md
    - 书籍/机器学习实战/07.集成方法-随机森林和AdaBoost.md
    - 书籍/机器学习实战/08.预测数值型数据-回归.md
    - 书籍/机器学习实战/09.树回归.md
    - 书籍/机器学习实战/10.k-means聚类.md
    - 书籍/机器学习实战/11.使用Apriori算法进行关联分析.md
    - 书籍/机器学习实战/12.使用FP-growth算法来高效发现频繁项集.md
    - 书籍/机器学习实战/13.利用PCA来简化数据.md
    - 书籍/机器学习实战/14.利用SVD简化数据.md
    - 书籍/机器学习实战/15.大数据与MapReduce.md
    - 书籍/机器学习实战/16.推荐系统.md
  - 深度学习:
    - 书籍/深度学习/DeepLearning.md
- 学习:
  - 学习/index.md
  - tensorflow:
    - 学习/tensorflow/如何选择优化器 optimizer.md
  - 深度学习:
    - 学习/深度学习/主成分分析-2.md
    - 学习/深度学习/主成分分析.md
    - 学习/深度学习/最小二乘法.md
    - 学习/深度学习/矩阵分解.md
    - 学习/深度学习/矩阵求导.md
- 工具:
  - 工具/About.md
  - 工具/Cheatsheet.md
  - 工具/index.md
  - 工具/shell显示时间.md
  - 常用工具:
    - 工具/常用工具/10分钟上手Latex.md
    - 工具/常用工具/10分钟上手Pandas.md
    - 工具/常用工具/10分钟上手Python.md
- 文章:
  - 文章/index.md
- 日常:
  - 日常/index.md
  - test:
    - 日常/test/testtest.md
repo_name: 1007530194/Diary
repo_url: https://github.com/1007530194/Diary
site_author: NiuLiangtao
site_description: Nothing is impossible
site_name: Blog of NiuLiangtao
site_url: https://1007530194.github.io/Diary/
theme:
  custom_dir: material
  favicon: assets/images/favicon.png
  feature:
    tabs: true
  font:
    code: Roboto Mono
    text: Roboto
  include_search_page: false
  language: en
  logo:
    icon: 
  name: null
  palette:
    accent: indigo
    primary: indigo
  search_index_only: true
  static_templates:
  - 404.html
